export const fuelProducts = [
  { id: 1, name: 'Unleaded Petrol' },
  { id: 2, name: 'Premium Unleaded' },
  { id: 4, name: 'Diesel' },
  { id: 5, name: 'LPG' },
  { id: 6, name: '98 RON' },
  { id: 10, name: 'E85' },
  { id: 11, name: 'Brand diesel' },
]

export const locations = [
  { id: 25, name: 'Metro: North of River' },
  { id: 26, name: 'Metro: South of River' },
  { id: 27, name: 'Metro: East/Hills' },
  { id: 15, name: 'Albany' },
  { id: 28, name: 'Augusta / Margaret River' },
  { id: 30, name: 'Bridgetown / Greenbushes' },
  { id: 1, name: 'Boulder' },
  { id: 2, name: 'Broome' },
  { id: 16, name: 'Bunbury' },
  { id: 3, name: 'Busselton (Townsite)' },
  { id: 29, name: 'Busselton (Shire)' },
  { id: 19, name: 'Capel' },
  { id: 4, name: 'Carnarvon' },
  { id: 33, name: 'Cataby' },
  { id: 5, name: 'Collie' },
  { id: 34, name: 'Coolgardie' },
  { id: 35, name: 'Cunderdin' },
  { id: 31, name: 'Donnybrook / Balingup' },
  { id: 36, name: 'Dalwallinu' },
  { id: 6, name: 'Dampier' },
  { id: 20, name: 'Dardanup' },
  { id: 37, name: 'Denmark' },
  { id: 38, name: 'Derby' },
  { id: 39, name: 'Dongara' },
  { id: 7, name: 'Esperance' },
  { id: 40, name: 'Exmouth' },
  { id: 41, name: 'Fitzroy Crossing' },
  { id: 17, name: 'Geraldton' },
  { id: 21, name: 'Greenough' },
  { id: 22, name: 'Harvey' },
  { id: 42, name: 'Jurien' },
  { id: 8, name: 'Kalgoorlie' },
  { id: 43, name: 'Kambalda' },
  { id: 9, name: 'Karratha' },
  { id: 44, name: 'Kellerberrin' },
  { id: 45, name: 'Kojonup' },
  { id: 10, name: 'Kununurra' },
  { id: 18, name: 'Mandurah' },
  { id: 32, name: 'Manjimup' },
  { id: 58, name: 'Meckering' },
  { id: 46, name: 'Meekatharra' },
  { id: 47, name: 'Moora' },
  { id: 48, name: 'Mount Barker' },
  { id: 61, name: 'Munglinup' },
  { id: 23, name: 'Murray' },
  { id: 11, name: 'Narrogin' },
  { id: 49, name: 'Newman' },
  { id: 50, name: 'Norseman' },
  { id: 60, name: 'North Bannister' },
  { id: 12, name: 'Northam' },
  { id: 62, name: 'Northam (Shire)' },
  { id: 13, name: 'Port Hedland' },
  { id: 51, name: 'Ravensthorpe' },
  { id: 57, name: 'Regans Ford' },
  { id: 14, name: 'South Hedland' },
  { id: 53, name: 'Tammin' },
  { id: 24, name: 'Waroona' },
  { id: 54, name: 'Williams' },
  { id: 55, name: 'Wubin' },
  { id: 59, name: 'Wundowie' },
  { id: 56, name: 'York' },
]

export const fuelBrands = [
  { id: 29, name: '7-Eleven' },
  { id: 2, name: 'Ampol' },
  { id: 41, name: 'Astron' },
  { id: 34, name: 'Atlas' },
  { id: 3, name: 'Better Choice' },
  { id: 4, name: 'BOC' },
  { id: 5, name: 'BP' },
  { id: 39, name: 'Burk' },
  { id: 6, name: 'Caltex' },
  { id: 36, name: 'CGL fuel' },
  { id: 20, name: 'Coles Express' },
  { id: 32, name: 'Costco' },
  { id: 24, name: 'Eagle' },
  { id: 35, name: 'EG Ampol' },
  { id: 25, name: 'FastFuel 24/7' },
  { id: 7, name: 'Gull' },
  { id: 15, name: 'Independent' },
  { id: 10, name: 'Liberty' },
  { id: 30, name: 'Metro Petroleum' },
  { id: 11, name: 'Mobil' },
  { id: 42, name: 'OTR' },
  { id: 40, name: 'Petro Fuels' },
  { id: 38, name: 'Phoenix' },
  { id: 26, name: 'Puma' },
  { id: 43, name: 'Reddy Express' },
  { id: 14, name: 'Shell' },
  { id: 23, name: 'United' },
  { id: 27, name: 'Vibe' },
  { id: 31, name: 'WA Fuels' },
  { id: 37, name: 'X Convenience' },
]
